FROM golang:1.10

MAINTAINER jackliu97@gmail.com

WORKDIR /app

RUN go get github.com/gorilla/mux
RUN go get github.com/go-sql-driver/mysql
RUN go get golang.org/x/crypto/bcrypt
RUN go get github.com/spf13/viper
RUN go get github.com/gorilla/websocket